spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL_DEV}
    username: ${MYSQL_USERNAME_DEV}
    password: ${MYSQL_PASSWORD_DEV}

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect

  data:
    redis:
      host: hotdeal-redis
      port: 6379

  mail:
    username: ${GOOGLE_SMTP_ACCOUNT}
    password: ${GOOGLE_SMTP_PW}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true

jwt:
  secret: ${JWT_SECRET}
