spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL_DEV}
    username: ${MYSQL_USERNAME_DEV}
    password: ${MYSQL_PASSWORD_DEV}

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect

  data:
    redis:
      host: localhost
      port: 6379

  mail: # prod - cloud config
    username: ${GOOGLE_SMTP_ACCOUNT}
    password: ${GOOGLE_SMTP_PW}
